Fixed wrong backslash and double quote escape
Cause of error:
ValueError: Invalid \escape: line 1 column 7891 (char 7890)
WebsiteParsingError: Unable to extract reactContext

Due to backslash in the profile name