Fixed build_media_tag exception
This fix the error:
Exception: build_media_tag: unable to find audio data

Due to unmanaged behavior on the video pause case,
the steps to reproduce the issue:
- Play a netflix video
- Pause the current video
- Return to Kodi home without Stop the video
- Play a non-netflix video, while the other is in the background