Replaced HTTPX to Requests module
Our local old httpx version have problems with new pyhton versions e.g. 3.11
update the httpx to last version (0.25) cause folowing errors
httpcore.RemoteProtocolError: Server disconnected
at least while testing on android, that make almost unusuable the addon
so for now has been reverted to Requests module.
With this will be lost http2 compatibility but since the login is broken, should be not a problem.
NOTE: KeepAlive fix has been not reintroduced intentionally.