AuthURL is changed while the profile change is executed
Seem the cause of error:

HTTPError: 401 Client Error: Unauthorized for url:
https://www.------.com/api/shakti/v7bb27746/playlistop

when try to add/remove to mylist after switching to another profile