Fixed wrong path in linux systems
is the cause error in addon/service starts:
Error Type: <type 'exceptions.LookupError'>
Error Contents: no codec search functions registered: can't find
encoding
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/plugin.video.netflix/service.py", line 18,
in <module>
g.init_globals(sys.argv)
File
"/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/globals.py",
line 217, in init_globals
self.PATH = unquote(self.URL[2][1:]).decode('utf-8')
LookupError: no codec search functions registered: can't find encoding