Fixed edge case of getDirectory error
This fix the error of:
ERROR: XFILE::CDirectory::GetDirectory - Error getting ...
due to missing delimiter at the end of path