website: fixed "Check your credentials" after login
the reactContext json content of userdata contained some line feed '\n' not escaped caused error in loading json

File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/api/website.py", line 167, in extract_json
return json.loads(json_str)
ValueError: Invalid control character at: line 1 column 66301 (char 66300)